In [1]:
%pip install qiskit qiskit-aer

   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 8.5 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.6 MB 5.9 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.6 MB 6.5 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.6 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.6 MB 6.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.6 MB 6.9 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 6.6 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Define the Pauli gates
x_gate = np.array([[0, 1], [1, 0]])
y_gate = np.array([[0, -1j], [1j, 0]])
z_gate = np.array([[1, 0], [0, -1]])

# Define the Hadamard gate
h_gate = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])

# Define the S gate
s_gate = np.array([[1, 0], [0, 1j]])

# Define the T gate
t_gate = np.array([[1, 0], [0, np.exp(1j * np.pi / 4)]])

print("Pauli X gate:\n", x_gate)
print("\nPauli Y gate:\n", y_gate)
print("\nPauli Z gate:\n", z_gate)
print("\nHadamard gate:\n", h_gate)
print("\nS gate:\n", s_gate)
print("\nT gate:\n", t_gate)

Pauli X gate:
 [[0 1]
 [1 0]]

Pauli Y gate:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

Pauli Z gate:
 [[ 1  0]
 [ 0 -1]]

Hadamard gate:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

S gate:
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

T gate:
 [[1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]]


In [3]:
# Define the |0⟩ state vector
zero_state = np.array([[1], [0]])

# Print the state vector
print("Initialized |0⟩ state vector:\n", zero_state)

Initialized |0⟩ state vector:
 [[1]
 [0]]


In [4]:
# Apply the X gate
state_after_x = np.dot(x_gate, zero_state)

# Apply the Y gate
state_after_y = np.dot(y_gate, state_after_x)

# Apply the Z gate
state_after_z = np.dot(z_gate, state_after_y)

# Apply the H gate
state_after_h = np.dot(h_gate, state_after_z)

# Apply the S gate
state_after_s = np.dot(s_gate, state_after_h)

# Apply the T gate
final_state = np.dot(t_gate, state_after_s)

# Print the final state vector
print("Final state vector after applying X, Y, Z, H, S, T:\n", final_state)

Final state vector after applying X, Y, Z, H, S, T:
 [[0. -0.70710678j]
 [0.5+0.5j       ]]


In [7]:
from qiskit import QuantumCircuit

In [8]:
# Create a QuantumCircuit object with one qubit
qc = QuantumCircuit(1)

# Add the X, Y, Z, H, S, and T gates to the circuit
qc.x(0)
qc.y(0)
qc.z(0)
qc.h(0)
qc.s(0)
qc.t(0)

# Draw the quantum circuit
print(qc.draw())

   ┌───┐┌───┐┌───┐┌───┐┌───┐┌───┐
q: ┤ X ├┤ Y ├┤ Z ├┤ H ├┤ S ├┤ T ├
   └───┘└───┘└───┘└───┘└───┘└───┘


In [9]:
from qiskit_aer import Aer
from qiskit import QuantumCircuit

# Recreate the quantum circuit with one qubit and one classical bit
qc = QuantumCircuit(1, 1)

# Add the X, Y, Z, H, S, and T gates to the circuit
qc.x(0)
qc.y(0)
qc.z(0)
qc.h(0)
qc.s(0)
qc.t(0)

# Get the qasm_simulator from the imported Aer backend
simulator = Aer.get_backend('qasm_simulator')

# Add a measurement gate to the quantum circuit qc on the single qubit and classical bit
qc.measure(0, 0)

# Transpile the circuit for the qasm_simulator
transpiled_qc = qc.copy()

# Run the transpiled circuit on the simulator with 10000 shots
job = simulator.run(transpiled_qc, shots=10000)

# Get the results from the job
result = job.result()

# Get the counts of the measurement outcomes from the results
counts = result.get_counts(transpiled_qc)

# Print the counts
print("\nMeasurement outcomes (counts):", counts)


Measurement outcomes (counts): {'0': 5009, '1': 4991}


In [10]:
# The counts were obtained in the previous step and stored in the 'counts' variable.
# The total number of shots was 10000.
total_shots = 10000

# Get the counts for '0' and '1'. If a key is not present, its count is 0.
counts_0 = counts.get('0', 0)
counts_1 = counts.get('1', 0)

# Calculate the probabilities
prob_0 = counts_0 / total_shots
prob_1 = counts_1 / total_shots

print(f"Counts for '0': {counts_0}")
print(f"Counts for '1': {counts_1}")
print(f"Probability of measuring '0': {prob_0}")
print(f"Probability of measuring '1': {prob_1}")

# Discuss the implications
print("\nAnalysis of Simulation Results:")
print(f"The simulation ran {total_shots} times.")
print(f"The observed counts show that the outcome '0' occurred {counts_0} times and '1' occurred {counts_1} times.")
print(f"This translates to a probability of {prob_0:.4f} for measuring '0' and {prob_1:.4f} for measuring '1'.")
print("These probabilities are approximately 0.5 for both outcomes.")
print("This suggests that the final state of the qubit, just before measurement, is a superposition where the amplitudes of the |0⟩ and |1⟩ states have roughly equal magnitude.")
print("The probabilistic nature of quantum measurement causes the observed counts to fluctuate around the theoretically expected probabilities derived from the squared magnitudes of the final state vector amplitudes.")

Counts for '0': 5009
Counts for '1': 4991
Probability of measuring '0': 0.5009
Probability of measuring '1': 0.4991

Analysis of Simulation Results:
The simulation ran 10000 times.
The observed counts show that the outcome '0' occurred 5009 times and '1' occurred 4991 times.
This translates to a probability of 0.5009 for measuring '0' and 0.4991 for measuring '1'.
These probabilities are approximately 0.5 for both outcomes.
This suggests that the final state of the qubit, just before measurement, is a superposition where the amplitudes of the |0⟩ and |1⟩ states have roughly equal magnitude.
The probabilistic nature of quantum measurement causes the observed counts to fluctuate around the theoretically expected probabilities derived from the squared magnitudes of the final state vector amplitudes.


In [11]:
r_gate = np.dot(np.dot(h_gate, s_gate), h_gate)
x_sqrt_gate = np.array([[1/np.sqrt(2), -1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)]], dtype=complex)

print("Matrix for R (HSH):\n", r_gate)
print("\nMatrix for sqrt(X) (Ry(pi/2)):\n", x_sqrt_gate)
are_equal_direct = np.allclose(r_gate, x_sqrt_gate)
are_equal_global_phase_pi = np.allclose(r_gate, -x_sqrt_gate) # Check for a global phase of pi

print("\nIs R approximately equal to sqrt(X)?", are_equal_direct)
print("Is R approximately equal to -sqrt(X) (global phase of pi)?", are_equal_global_phase_pi)
print("\nLet's calculate R^2:")
r_squared = np.dot(r_gate, r_gate)
print("Matrix for R^2:\n", r_squared)
print("\nMatrix for X:\n", x_gate)
print("\nIs R^2 approximately equal to X?", np.allclose(r_squared, x_gate))

Matrix for R (HSH):
 [[0.5+0.5j 0.5-0.5j]
 [0.5-0.5j 0.5+0.5j]]

Matrix for sqrt(X) (Ry(pi/2)):
 [[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]

Is R approximately equal to sqrt(X)? False
Is R approximately equal to -sqrt(X) (global phase of pi)? False

Let's calculate R^2:
Matrix for R^2:
 [[0.-2.46519033e-32j 1.+0.00000000e+00j]
 [1.+0.00000000e+00j 0.+2.46519033e-32j]]

Matrix for X:
 [[0 1]
 [1 0]]

Is R^2 approximately equal to X? True
